"""Render an approved setup plan into a project. Deterministic; no AI.

Usage:
  python3 render.py --target DIR --plan plan.json [--dry-run]
  python3 render.py --target DIR [--dry-run]          # re-render (upgrade) from .claude/setup-manifest.json
  python3 render.py --target DIR --plan plan.json --show CLAUDE.md   # print one rendered file, write nothing

File rules:
  owned files  - CREATE if absent; SKIP if present but not generated by us;
                 UPGRADE if generated by us and unedited; KEEP-EDITED (diff shown) if the user edited it.
  merged files - .claude/settings.json, .mcp.json, .gitignore, .env.example: union-merged, never clobbered.
Exit codes: 0 ok · 2 invalid plan (missing vars, unknown template, literal secret) · nothing written on 2.
"""
import difflib
import hashlib
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PLUGIN = os.path.dirname(HERE)
TPL = os.path.join(PLUGIN, "templates")
VAR = re.compile(r"\{\{([A-Z0-9_]+)(?:\|(json|yamllist))?\}\}")
SECRET = re.compile(r"(sk-[A-Za-z0-9_-]{16,}|ghp_[A-Za-z0-9]{20,}|github_pat_\w{20,}|xox[abprs]-[\w-]{10,}"
                    r"|AKIA[0-9A-Z]{16}|eyJ[\w-]{15,}\.[\w-]{10,}|glpat-[\w-]{20,})")
LEVELS = {
    "light": ["guard", "session_context"],
    "standard": ["guard", "session_context", "stop_gate", "approval_capture"],
    "strict": ["guard", "session_context", "stop_gate", "approval_capture", "scope_check", "test_on_stop"],
}
TRACKED_LEVELS = {"standard", "strict"}  # task state machines + approval capture
TRACKER_FILES = ["_common.py", "init_machine.py", "transition.py", "assert_state.py", "query_state.py",
                 "resume.py", "render_reports.py"]
HOOK_EVENTS = {  # hook -> (event, matcher)
    "session_context": ("SessionStart", "startup|resume|clear|compact"),
    "guard": ("PreToolUse", "Write|Edit|MultiEdit|NotebookEdit|Bash"),
    "scope_check": ("PreToolUse", "Write|Edit|MultiEdit"),
    "format_on_edit": ("PostToolUse", "Write|Edit|MultiEdit"),
    "stop_gate": ("Stop", None),
    "test_on_stop": ("Stop", None),
    "approval_capture": ("UserPromptSubmit", None),
}
CORE_AGENTS = ["explorer", "implementer", "verifier", "reviewer"]
SEED_FILES = {"docs/STATE.md", "docs/ARCHITECTURE.md"}  # created once, then owned by the user
GITIGNORE_REQUIRED = [".env", ".env.*", "!.env.example", "CLAUDE.local.md", ".claude/settings.local.json",
                      ".claude/state-machine/.state-machine/*/.lock", ".claude/state-machine/.state-machine/*/*.tmp"]


class PlanError(Exception):
    pass


def version():
    with open(os.path.join(PLUGIN, ".claude-plugin", "plugin.json"), encoding="utf-8") as f:
        return json.load(f)["version"]


def read_plugin(rel):
    with open(os.path.join(PLUGIN, rel), encoding="utf-8") as f:
        return f.read()


def bootstrap_state(target):
    """Current state of the project's setup machine, replayed from its event log (None if absent)."""
    sys.path.insert(0, os.path.join(PLUGIN, "tracker", "scripts"))
    import _common as c
    from pathlib import Path
    d = Path(target) / ".claude" / "state-machine" / ".state-machine" / "bootstrap"
    if not (d / "machine.json").exists():
        return None
    return c.replay_state(c.load_json(d / "machine.json"), c.read_events(d / "events.jsonl"))


def tpl(rel):
    path = os.path.join(TPL, rel)
    if not os.path.exists(path):
        raise PlanError(f"unknown template: {rel}")
    with open(path, encoding="utf-8") as f:
        return f.read()


def fill(text, variables, where, missing):
    def sub(m):
        name, flt = m.group(1), m.group(2)
        if name not in variables:
            missing.append(f"{where}: {name}")
            return m.group(0)
        v = variables[name]
        if flt == "json":
            return json.dumps(v)
        if flt == "yamllist":
            return "\n".join(f'  - "{x}"' for x in (v if isinstance(v, list) else [v]))
        return "\n".join(map(str, v)) if isinstance(v, list) else str(v)
    return VAR.sub(sub, text)


FM_LINE = re.compile(r"^([A-Za-z][\w-]*): (.+)$")
YAML_UNSAFE = re.compile(r"(: | #|^[\[\]{}&*!|>'\"%@`,?-])")


def safe_frontmatter(text):
    """Quote scalar frontmatter values that filled-in vars made invalid YAML (e.g. 'a: b' in a description)."""
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---", 4)
    if end < 0:
        return text
    out = []
    for line in text[4:end].split("\n"):
        m = FM_LINE.match(line)
        if m and YAML_UNSAFE.search(m.group(2)) and not (m.group(2).startswith('"') and m.group(2).endswith('"')):
            line = f"{m.group(1)}: {json.dumps(m.group(2))}"
        out.append(line)
    return "---\n" + "\n".join(out) + text[end:]


def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def frontmatter(text, key):
    m = re.search(rf"^{key}:\s*(.+)$", text.split("\n---", 1)[0], re.M)
    v = m.group(1).strip() if m else ""
    return json.loads(v) if v.startswith('"') and v.endswith('"') else v


def load_catalog():
    with open(os.path.join(PLUGIN, "catalog", "integrations.json"), encoding="utf-8") as f:
        return json.load(f)


def mcp_entries(plan, catalog):
    out = {}
    for item in plan.get("mcp", []):
        if isinstance(item, str):
            if item not in catalog["mcp_servers"]:
                raise PlanError(f"unknown MCP server '{item}' (not in catalog; pass a {{name: config}} object)")
            e = catalog["mcp_servers"][item]
            out[item] = {"config": e["config"], "permission": e["permission"], "env": e.get("env", []),
                         "oauth": e["config"].get("type") == "http" and not e["config"].get("headers")}
        else:
            for name, cfg in item.items():
                env = sorted(set(re.findall(r"\$\{([A-Z0-9_]+)", json.dumps(cfg))))
                out[name] = {"config": cfg, "permission": "ask", "env": env, "oauth": False}
    for name, e in out.items():
        blob = json.dumps(e["config"])
        if SECRET.search(blob):
            raise PlanError(f"MCP server '{name}' contains what looks like a literal secret; use ${{VAR}}")
        for section in ("env", "headers"):
            for k, v in (e["config"].get(section) or {}).items():
                if isinstance(v, str) and v and "${" not in v:
                    raise PlanError(f"MCP server '{name}' {section}.{k} must reference an env var like ${{{k}}}")
    return out


def build(plan, target):
    """Return (owned: {path: (template, text)}, merged: {path: fn(existing_text|None)->text}, missing)."""
    level = plan.get("level", "standard")
    if level not in LEVELS:
        raise PlanError(f"level must be one of {list(LEVELS)}")
    py = plan.get("python") or ("python" if os.name == "nt" else "python3")
    catalog = load_catalog()
    mcps = mcp_entries(plan, catalog)
    v = dict(plan.get("vars", {}))
    missing, owned = [], {}

    def add(path, template, extra=None):
        owned[path] = (template, safe_frontmatter(fill(tpl(template), {**v, **(extra or {})}, path, missing)))

    modules = plan.get("modules", [])
    env_vars = sorted({e for m in mcps.values() for e in m["env"]})
    oauth = sorted(n for n, m in mcps.items() if m["oauth"])
    mcp_setup = ""
    if mcps:
        mcp_setup = f"\n## MCP servers (`.mcp.json`): {', '.join(sorted(mcps))}\n"
        if env_vars:
            mcp_setup += f"- Copy `.env.example` to `.env` (or export) and set: {', '.join(env_vars)}. Never commit values.\n"
        if oauth:
            mcp_setup += f"- Sign in yourself with `/mcp`: {', '.join(oauth)}.\n"
    computed = {
        "GUARDRAIL_LEVEL": level, "MCP_SETUP": mcp_setup,
        "MODULE_MAP": ", ".join(f"`{m['path']}/`" for m in modules) or "single module (see CLAUDE.md Layout)",
    }
    v.update({k: val for k, val in computed.items() if k not in v})

    # agents
    agent_items = CORE_AGENTS + [a for a in plan.get("agents", []) if a not in CORE_AGENTS]
    agent_lines = []
    for a in agent_items:
        template, extra = (a, {}) if isinstance(a, str) else (a["template"], a.get("vars", {}))
        name = extra.get("AGENT_NAME", template)
        add(f".claude/agents/{name}.md", f"agents/{template}.md", extra)
        text = owned[f".claude/agents/{name}.md"][1]
        desc = frontmatter(text, "description").split(". ")[0].rstrip(".")
        agent_lines.append(f"- `{name}` ({frontmatter(text, 'model')}): {desc}.")

    # hooks
    hooks = list(LEVELS[level]) + (["format_on_edit"] if plan.get("format_on_edit") else [])
    for h in hooks + ["selftest"]:
        add(f".claude/hooks/{h}.py", f"hooks/{h}.py")

    # rules, skills, guard lists
    for r in plan.get("rules", []):
        template, extra = (r, {}) if isinstance(r, str) else (r["template"], r.get("vars", {}))
        add(f".claude/rules/{template}.md", f"rules/{template}.md", extra)
    for s in ("task", "checkpoint"):
        add(f".claude/skills/{s}/SKILL.md", f"skills/{s}/SKILL.md")
    if level in TRACKED_LEVELS:  # task state machines: tracker + definition + CLI, copied verbatim
        add(".claude/state-machine/state_cli.py", "state-machine/state_cli.py")
        add(".claude/state-machine/task.json", "state-machine/task.json")
        for f in TRACKER_FILES:
            owned[f".claude/state-machine/tracker/scripts/{f}"] = (f"tracker/scripts/{f}", read_plugin(f"tracker/scripts/{f}"))
    add(".claude/protected.txt", "protected.txt", {"PROTECTED_LINES": plan.get("protected", [])})
    add(".claude/write-allow.txt", "write-allow.txt", {"WRITE_ALLOW_LINES": plan.get("write_allow", [])})

    # modules
    for m in modules:
        add(f"{m['path']}/CLAUDE.md", "CLAUDE.module.md", {"MODULE": m["path"], **m.get("vars", {})})

    v.setdefault("AGENTS_LIST", agent_lines)
    for path, template in [("CLAUDE.md", "CLAUDE.md"), ("docs/STATE.md", "docs/STATE.md"),
                           ("docs/ARCHITECTURE.md", "docs/ARCHITECTURE.md"),
                           ("docs/adr/0000-template.md", "docs/adr/0000-template.md"),
                           ("specs/TASK-TEMPLATE.md", "specs/TASK-TEMPLATE.md")]:
        add(path, template)

    # merged files
    with open(os.path.join(TPL, "settings", "base.json"), encoding="utf-8") as f:
        base = json.load(f)
    perms = plan.get("permissions", {})
    for kind in ("allow", "ask", "deny"):
        base["permissions"][kind] += perms.get(kind, [])
    base["permissions"]["allow"].append(f"Bash({py} .claude/hooks/selftest.py)")
    for name, m in mcps.items():
        base["permissions"]["allow" if m["permission"] == "allow" else "ask"].append(f"mcp__{name}")
    hooks_cfg = {}
    for h in hooks:
        event, matcher = HOOK_EVENTS[h]
        entry = {"type": "command", "command": f'{py} "$CLAUDE_PROJECT_DIR/.claude/hooks/{h}.py"', "timeout": 330 if h == "test_on_stop" else 30}
        groups = hooks_cfg.setdefault(event, [])
        group = next((g for g in groups if g.get("matcher") == matcher), None)
        if not group:
            group = {"matcher": matcher, "hooks": []} if matcher else {"hooks": []}
            groups.append(group)
        group["hooks"].append(entry)
    base["hooks"] = hooks_cfg
    plugins = plan.get("plugins", {})
    if plugins.get("enable") or plugins.get("disable"):
        base["enabledPlugins"] = {**{p: False for p in plugins.get("disable", [])},
                                  **{p: True for p in plugins.get("enable", [])}}
    if plugins.get("marketplaces"):
        base["extraKnownMarketplaces"] = plugins["marketplaces"]

    merged = {".claude/settings.json": lambda old: merge_settings(old, base),
              ".gitignore": lambda old: merge_lines(old, GITIGNORE_REQUIRED + plan.get("gitignore", []))}
    if mcps:
        merged[".mcp.json"] = lambda old: merge_mcp(old, {n: m["config"] for n, m in mcps.items()})
    if env_vars:
        merged[".env.example"] = lambda old: merge_lines(old, [f"{e}=" for e in env_vars], key=lambda l: l.split("=")[0])
    return owned, merged, missing


def merge_settings(old, new):
    cur = json.loads(old) if old else {}
    for k, val in new.items():
        if k == "permissions":
            p = cur.setdefault("permissions", {})
            for kind, rules in val.items():
                if isinstance(rules, list):
                    p[kind] = p.get(kind, []) + [r for r in rules if r not in p.get(kind, [])]
                else:
                    p.setdefault(kind, rules)
        elif k == "hooks":
            h = cur.setdefault("hooks", {})
            for event, groups in val.items():
                cur_groups = h.setdefault(event, [])
                existing = {e.get("command") for grp in cur_groups for e in grp.get("hooks", [])}
                for g in groups:
                    for e in g["hooks"]:
                        if e["command"] in existing:
                            continue
                        target = next((x for x in cur_groups if x.get("matcher") == g.get("matcher")
                                       and any("claude/hooks/" in y.get("command", "") for y in x.get("hooks", []))), None)
                        if target is None:
                            target = {**({"matcher": g["matcher"]} if g.get("matcher") else {}), "hooks": []}
                            cur_groups.append(target)
                        target["hooks"].append(e)
                        existing.add(e["command"])
        elif isinstance(val, dict):
            cur.setdefault(k, {}).update({kk: vv for kk, vv in val.items() if kk not in cur[k]})
        else:
            cur.setdefault(k, val)
    return json.dumps(cur, indent=2) + "\n"


def merge_mcp(old, servers):
    cur = json.loads(old) if old else {}
    s = cur.setdefault("mcpServers", {})
    for name, cfg in servers.items():
        s.setdefault(name, cfg)  # never replace a server the user already configured
    return json.dumps(cur, indent=2) + "\n"


def merge_lines(old, required, key=lambda l: l):
    lines = (old or "").splitlines()
    have = {key(l.strip()) for l in lines}
    add = [r for r in required if key(r) not in have]
    if not add:
        return old if old is not None else ""
    head = ("\n".join(lines) + "\n") if lines else ""
    return head + ("# added by claude-project-setup\n" if lines else "") + "\n".join(add) + "\n"


def read(path):
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except OSError:
        return None


def main(argv):
    flags = {a: argv[i + 1] for i, a in enumerate(argv) if a in ("--target", "--plan", "--show") and i + 1 < len(argv)}
    dry = "--dry-run" in argv
    target = os.path.realpath(flags.get("--target", "."))
    manifest_path = os.path.join(target, ".claude", "setup-manifest.json")
    manifest = json.loads(read(manifest_path) or "{}")
    if "--plan" in flags:
        plan = json.loads(read(flags["--plan"]) or "null")
        if plan is None:
            print(f"cannot read plan {flags['--plan']}", file=sys.stderr)
            return 2
    elif manifest.get("plan"):
        plan = manifest["plan"]
    else:
        print("no --plan and no .claude/setup-manifest.json to upgrade from", file=sys.stderr)
        return 2
    try:
        owned, merged, missing = build(plan, target)
    except PlanError as e:
        print(f"PLAN ERROR: {e}", file=sys.stderr)
        return 2
    known = manifest.get("files", {})
    will_skip = {rel for rel in owned if os.path.exists(os.path.join(target, rel))
                 and (rel not in known or rel in SEED_FILES)}
    missing = [m for m in missing if m.split(": ")[0] not in will_skip]
    if missing:
        print("PLAN ERROR: missing variables (set them in plan.vars, or 'n/a'):\n  " + "\n  ".join(missing), file=sys.stderr)
        return 2
    if "--show" in flags:
        rel = flags["--show"]
        if rel in owned:
            print(owned[rel][1], end="")
        elif rel in merged:
            print(merged[rel](read(os.path.join(target, rel))), end="")
        else:
            print(f"{rel} is not produced by this plan", file=sys.stderr)
            return 2
        return 0

    actions, writes, new_files = [], {}, {}
    for rel, (template, text) in sorted(owned.items()):
        cur = read(os.path.join(target, rel))
        new_files[rel] = {"template": template, "sha256": sha(text)}
        if cur is None:
            actions.append(("CREATE", rel, ""))
            writes[rel] = text
        elif rel in SEED_FILES:
            actions.append(("KEEP-SEED", rel, "created once; yours to maintain") if rel in known
                           else ("SKIP", rel, "exists; kept as is"))
            new_files.pop(rel)
        elif rel not in known:
            actions.append(("SKIP", rel, "exists and was not generated by this plugin; merge by hand"))
            new_files.pop(rel)
        elif sha(cur) == sha(text):
            actions.append(("UNCHANGED", rel, ""))
        elif sha(cur) == known[rel]["sha256"]:
            actions.append(("UPGRADE", rel, ""))
            writes[rel] = text
        else:
            diff = list(difflib.unified_diff(cur.splitlines(), text.splitlines(), "yours", "template", lineterm="", n=1))
            actions.append(("KEEP-EDITED", rel, "you edited it; template diff:\n      " + "\n      ".join(diff[:30])))
            new_files[rel] = known[rel]
    for rel, fn in sorted(merged.items()):
        cur = read(os.path.join(target, rel))
        text = fn(cur)
        if cur == text:
            actions.append(("UNCHANGED", rel, "merged"))
        else:
            actions.append(("MERGE" if cur is not None else "CREATE", rel, "union-merged" if cur else ""))
            writes[rel] = text
        new_files[rel] = {"template": "merged", "sha256": sha(text)}

    for act, rel, note in actions:
        print(f"{act:<12} {rel}" + (f"  ({note})" if note else ""))
    print(f"\n{'DRY RUN: nothing written. ' if dry else ''}{len(writes)} file(s) to write, "
          f"{sum(1 for a in actions if a[0] == 'SKIP')} skipped, "
          f"{sum(1 for a in actions if a[0] == 'KEEP-EDITED')} kept (edited).")
    if dry:
        return 0
    first_setup = not known
    if first_setup and "--plan" in flags:
        st = bootstrap_state(target)
        if st != "APPROVED":
            print(f"REFUSED: the setup plan isn't approved yet (bootstrap state: {st or 'not started'}). "
                  "The user must reply 'approved' to the setup plan; the approval hook records it, then run "
                  "`state_cli.py move bootstrap approve`.", file=sys.stderr)
            return 3
    for rel, text in writes.items():
        path = os.path.join(target, rel)
        os.makedirs(os.path.dirname(path) or target, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    os.makedirs(os.path.dirname(manifest_path), exist_ok=True)
    with open(manifest_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump({"generator": "claude-project-setup", "version": version(), "plan": plan,
                   "files": new_files}, f, indent=2)
        f.write("\n")
    if bootstrap_state(target) == "APPROVED":
        cli = os.path.join(TPL, "state-machine", "state_cli.py")
        subprocess.run([sys.executable, cli, "move", "bootstrap", "rendered"], cwd=target, capture_output=True,
                       env=dict(os.environ, CLAUDE_PROJECT_DIR=target, PYTHONDONTWRITEBYTECODE="1"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
